import React from 'react';

// ============================================================================
// LETTER ENGINE: ICBC FORMAL SUBMISSION TEMPLATE
// Reconciles against Master_Submission_DA57244_2026-04-24.html
// ============================================================================

export interface Exhibit {
  id: string;
  date: string;
  description: string;
  status: string;
}

export interface ICBCSubmissionProps {
  claimNumber: string;
  claimantName: string;
  claimantDOB: string;
  date: string;
  version: string;
  urgentAlert: {
    title: string;
    description: string;
    demand: string;
  };
  positions: {
    title: string;
    content: string;
  }[];
  exhibits: Exhibit[];
  noticeOfIntent: string;
  nodeId: string;
}

export const ICBCFormalSubmission: React.FC<ICBCSubmissionProps> = ({
  claimNumber,
  claimantName,
  claimantDOB,
  date,
  version,
  urgentAlert,
  positions,
  exhibits,
  noticeOfIntent,
  nodeId
}) => {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>ICBC CONSOLIDATED MASTER SUBMISSION - {claimNumber} - {version}</title>
        <style dangerouslySetInnerHTML={{ __html: `
          body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #1a1a1a; max-width: 900px; margin: 0 auto; padding: 40px; background-color: #fff; }
          .legal-header { border-bottom: 3px solid #000; padding-bottom: 20px; margin-bottom: 30px; text-align: center; }
          .legal-header h1 { margin: 0; font-size: 24pt; text-transform: uppercase; letter-spacing: 2px; }
          .legal-header p { margin: 5px 0; font-weight: bold; }
          .urgent-alert { background: #fee2e2; border: 2px solid #ef4444; padding: 20px; margin-bottom: 30px; border-radius: 4px; }
          .urgent-alert h2 { color: #b91c1c; margin-top: 0; }
          .claim-summary { background: #f8fafc; border: 1px solid #e2e8f0; padding: 20px; margin-bottom: 30px; }
          .evidence-table { width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 0.9em; }
          .evidence-table th { background: #1e293b; color: #fff; padding: 12px; text-align: left; }
          .evidence-table td { border: 1px solid #cbd5e1; padding: 10px; }
          .section-title { border-left: 5px solid #1e293b; padding-left: 15px; margin: 40px 0 20px; text-transform: uppercase; letter-spacing: 1px; }
          .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #cbd5e1; font-size: 0.8em; text-align: center; color: #64748b; }
          @media print { body { padding: 0; } .urgent-alert { border-color: #000; } }
        `}} />
      </head>
      <body>
        <div className="legal-header">
          <h1>Consolidated Master Submission</h1>
          <p>RE: ICBC CLAIM {claimNumber}</p>
          <p>CLAIMANT: {claimantName} (DOB: {claimantDOB})</p>
          <p>DATE: {date} | VERSION: {version}</p>
        </div>

        {urgentAlert && (
          <div className="urgent-alert">
            <h2>⚠️ URGENT: {urgentAlert.title}</h2>
            <p dangerouslySetInnerHTML={{ __html: urgentAlert.description }} />
            <p><strong>DEMAND:</strong> <span dangerouslySetInnerHTML={{ __html: urgentAlert.demand }} /></p>
          </div>
        )}

        <div className="claim-summary">
          <h3>POSITION SUMMARY</h3>
          <ul>
            {positions.map((pos, idx) => (
              <li key={idx}><strong>{pos.title}:</strong> <span dangerouslySetInnerHTML={{ __html: pos.content }} /></li>
            ))}
          </ul>
        </div>

        <h2 className="section-title">Schedule of Evidence (Exhibits)</h2>
        <table className="evidence-table">
          <thead>
            <tr>
              <th>Exhibit</th>
              <th>Date</th>
              <th>Document Description</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {exhibits.map((exhibit, idx) => (
              <tr key={idx}>
                <td>{exhibit.id}</td>
                <td>{exhibit.date}</td>
                <td>{exhibit.description}</td>
                <td>{exhibit.status}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <h2 className="section-title">Legal Notice of Intent</h2>
        <p dangerouslySetInnerHTML={{ __html: noticeOfIntent }} />

        <div className="footer">
          <p>Generated by KoRT Digital Advocate - {nodeId}</p>
          <p><em>Autonomy through Truth. Integrity through Proof.</em></p>
        </div>
      </body>
    </html>
  );
};

export default ICBCFormalSubmission;
